### ISSUE TITLE
Robot hover not working

### ISSUE THREAD

**Issue by erinmilling** [erinmilling/dsn1674-assignment-6#1]
I just went to show someone my robot, but I realize that it is not hovering anymore. It was working in class and you were helping me. I submitted it on friday and now its not working. Not sure why!

@thomasjbradley

**Comment by thomasjbradley** [comment]
It's working for me in Chrome and Firefox.
Do you remember what browser/device you showed it on?

**Comment by erinmilling** [comment]
Didn't work in Safari. Works in Chrome. My bad!
